# Generated by Django 2.2.5 on 2021-02-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210222_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='user',
            new_name='patient',
        ),
    ]
