# Generated by Django 2.2.5 on 2021-02-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_prediction_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='BMI',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='age',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='gul',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='ins',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='num_preg',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='ped',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='result',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='skt',
        ),
        migrations.AddField(
            model_name='prediction',
            name='Alopecia',
            field=models.IntegerField(choices=[(1, 'male'), (0, 'female'), (2, 'not specified')], default=2),
        ),
        migrations.AddField(
            model_name='prediction',
            name='Gender',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='Irritability',
            field=models.IntegerField(choices=[(1, 'male'), (0, 'female'), (2, 'not specified')], default=2),
        ),
        migrations.AddField(
            model_name='prediction',
            name='Partial_paresis',
            field=models.IntegerField(choices=[(1, 'male'), (0, 'female'), (2, 'not specified')], default=2),
        ),
        migrations.AddField(
            model_name='prediction',
            name='Polydipsia',
            field=models.IntegerField(choices=[(1, 'male'), (0, 'female'), (2, 'not specified')], default=2),
        ),
        migrations.AddField(
            model_name='prediction',
            name='Polyphagia',
            field=models.IntegerField(choices=[(1, 'male'), (0, 'female'), (2, 'not specified')], default=2),
        ),
        migrations.AddField(
            model_name='prediction',
            name='Polyuria',
            field=models.IntegerField(choices=[(1, 'male'), (0, 'female'), (2, 'not specified')], default=2),
        ),
        migrations.AddField(
            model_name='prediction',
            name='Prediction',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='Sudden_weight_loss',
            field=models.IntegerField(choices=[(1, 'male'), (0, 'female'), (2, 'not specified')], default=2),
        ),
        migrations.AddField(
            model_name='prediction',
            name='Visual_blurring',
            field=models.IntegerField(choices=[(1, 'male'), (0, 'female'), (2, 'not specified')], default=2),
        ),
        migrations.AddField(
            model_name='prediction',
            name='Weakness',
            field=models.IntegerField(choices=[(1, 'male'), (0, 'female'), (2, 'not specified')], default=2),
        ),
    ]
