# Generated by Django 2.2.5 on 2021-02-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210227_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='Gender',
            field=models.IntegerField(null=True),
        ),
    ]
