# Generated by Django 2.2.5 on 2021-03-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210301_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='Alopecia',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='Gender',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='Irritability',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='Partial_paresis',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='Polydipsia',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='Polyphagia',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='Polyuria',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='Sudden_weight_loss',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='Visual_blurring',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='Weakness',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female'), (2, 'Select Gender')], default=2),
        ),
    ]
