# Generated by Django 2.2.5 on 2021-03-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210302_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('Gender', models.IntegerField(choices=[(1, 'Male'), (0, 'Female'), (2, 'Gender')], default=2)),
                ('Polyuria', models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2)),
                ('Polydipsia', models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2)),
                ('Sudden_weight_loss', models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2)),
                ('Partial_paresis', models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2)),
                ('Polyphagia', models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2)),
                ('Irritability', models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2)),
                ('Alopecia', models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2)),
                ('Visual_blurring', models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2)),
                ('Weakness', models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Select')], default=2)),
                ('Prediction', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='prediction',
            name='Gender',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female'), (2, 'Gender')], default=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female'), (2, 'Gender')], default=2),
        ),
    ]
